### ISSUE TITLE
Add a footnote for Very Cool Software

### ISSUE THREAD

**Issue by levitanong** [syk0saje/git-gud#4]
While this is a funny joke, this might confuse newcomers. Adding a footnote preserves the joke, while still *actually* explaining the acronym to newcomers.

For example
```
Very Cool Software [1]
...
[1]: Just kidding, it actually means Virgin Coconut Soil
```

**Comment by syk0saje** [comment]
@levitanong make a PR you dumb shit

**Comment by levitanong** [comment]
Maybe

**Comment by syk0saje** [comment]
Fixed (???) by https://github.com/syk0saje/git-gud/pull/5
